# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['botiaver1.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('gold_analyzer.py', '.'),
        ('loss_analyzer.py', '.'),
        ('loss_protection_ai.py', '.'),
        ('stop_loss_analyzer.py', '.'),
        ('buy_specialist_ai.py', '.'),
        ('sell_specialist_ai.py', '.'),
        ('decision_arbitrator_ai.py', '.'),
        ('entry_point_ai.py', '.'),
        ('adaptive_parameters.py', '.'),
        # ⭐ NUEVOS MÓDULOS AGREGADOS
        ('safety_filters_manager.py', '.'),
        ('feedback_loop_ai.py', '.'),
        ('rapid_ops_validator.py', '.'),
        ('data_updater_module.py', '.'),
        ('data_loader_trainer.py', '.'),
        ('regime_detector.py', '.'),
        ('trend_model.py', '.'),
        ('reversion_model.py', '.'),
        ('bias_monitor.py', '.'),
        ('drift_detector.py', '.'),
    ],
    hiddenimports=[
        'MetaTrader5',
        'numpy',
        'numpy.core._multiarray_umath',
        'numpy.core',
        'pandas',
        'tkinter',
        'threading',
        'datetime',
        'collections',
        'time',
        'json',
        'os',
        'sys',
        'logging',
        'socket',
        'traceback',
        'weakref',
        'gold_analyzer',
        'loss_analyzer',
        'loss_protection_ai',
        'stop_loss_analyzer',
        'buy_specialist_ai',
        'sell_specialist_ai',
        'decision_arbitrator_ai',
        'entry_point_ai',
        'adaptive_parameters',
        # ⭐ NUEVOS MÓDULOS AGREGADOS
        'safety_filters_manager',
        'feedback_loop_ai',
        'rapid_ops_validator',
        'data_updater_module',
        'data_loader_trainer',
        'regime_detector',
        'trend_model',
        'reversion_model',
        'bias_monitor',
        'drift_detector',
        'sklearn',
        'sklearn.preprocessing',
        'sklearn.preprocessing._data',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Bot-IA-Ver9.2MultiAI',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
