# -*- mode: python ; coding: utf-8 -*-
import os
import sys
from PyInstaller.utils.hooks import collect_dynamic_libs, collect_data_files

block_cipher = None

# Collect XGBoost DLLs - método automático
xgboost_binaries = collect_dynamic_libs('xgboost')
xgboost_datas = collect_data_files('xgboost')

# ⭐ FORZAR inclusión manual de xgboost.dll si no fue encontrada
try:
    import xgboost
    xgb_lib_path = os.path.join(os.path.dirname(xgboost.__file__), 'lib', 'xgboost.dll')
    if os.path.exists(xgb_lib_path):
        # Agregar al directorio xgboost/lib/ para que XGBoost lo encuentre
        xgboost_binaries.append((xgb_lib_path, 'xgboost/lib'))
        print(f"[SPEC] XGBoost DLL agregada manualmente: {xgb_lib_path}")
except Exception as e:
    print(f"[SPEC] Error buscando xgboost.dll: {e}")

datas = [('logs', 'logs')]
datas += xgboost_datas
if os.path.exists('mi_sesion.session'):
    datas.append(('mi_sesion.session', '.'))

hiddenimports = [
    'MetaTrader5',
    'buy_specialist_ai',
    'sell_specialist_ai',
    'decision_arbitrator_ai',
    'loss_protection_ai',
    'feedback_loop_ai',
    'rapid_ops_validator',
    'entry_point_ai',
    'adaptive_parameters',
    'gold_analyzer',
    'loss_analyzer',
    'data_updater_module',
    'data_loader_trainer',
    'trade_logger',
    'auto_calibration',
    'regime_detector',
    'trend_model',
    'reversion_model',
    'bias_monitor',
    'drift_detector',
    'dynamic_weights',
    'meta_selector',
    'bot_integration_manager',
    'super_analyzer',
    'dynamic_score_calibration',
    'recovery_potential_enhanced',
    'spread_slippage_analyzer',
    'time_based_session_filter',
    'correlation_analyzer',
    'trend_change_detector',
    'multi_timeframe_analyzer',
    'numpy',
    'numpy.core',
    'numpy.core.multiarray',
    'numpy.core.umath',
    'numpy.core.numerictypes',
    'numpy.core._exceptions',
    'numpy.core._asarray',
    'numpy.core._ufunc_config',
    'numpy.lib',
    'numpy.lib.arraypad',
    'numpy.lib.arraysetops',
    'numpy.lib.arrayterator',
    'numpy.lib.function_base',
    'numpy.lib.index_tricks',
    'numpy.lib.mixins',
    'numpy.lib.nanfunctions',
    'numpy.lib.npyio',
    'numpy.lib.polynomial',
    'numpy.lib.scimath',
    'numpy.lib.shape_base',
    'numpy.lib.stride_tricks',
    'numpy.lib.twodim_base',
    'numpy.lib.type_check',
    'numpy.lib.utils',
    'numpy.random',
    'numpy.random.mtrand',
    'numpy.linalg',
    'numpy.fft',
    'numpy.ma',
    'numpy.polynomial',
    'pandas',
    'pandas.core',
    'pandas.core.arrays',
    'pandas.core.groupby',
    'pandas.core.algorithms',
    'pandas.core.indexes',
    'pandas.core.internals',
    'pandas.core.series',
    'pandas.core.frame',
    'pandas.core.generic',
    'pandas.io',
    'pandas.tseries',
    'pandas.tseries.frequencies',
    'pandas.tseries.offsets',
    'sklearn',
    'sklearn.preprocessing',
    'sklearn.utils',
    'sklearn.ensemble',
    'sklearn.tree',
    'sklearn.linear_model',
    'sklearn.metrics',
    'sklearn.model_selection',
    'sklearn.base',
    'sklearn.pipeline',
    'sklearn.decomposition',
    'xgboost',
    'xgboost.sklearn',
    'joblib',
    'unittest',
    'pickle',
    'json',
    'logging',
    'datetime',
    'collections',
    'pathlib',
    'threading',
    'time',
    'sys',
    'os',
    'io',
    'math',
    'random',
    'statistics',
    'decimal',
    'itertools',
    'functools',
    'operator',
    're',
    'shutil',
    'tempfile',
    'subprocess',
    'multiprocessing',
    'queue',
    'ssl',
    'socket',
    'http',
    'http.client',
    'urllib',
    'urllib.request',
    'urllib.parse',
    'requests',
    'certifi',
    'chardet',
    'idna',
    'urllib3',
    'zipfile',
    'tarfile',
    'gzip',
    'bz2',
    'lzma',
    'xml',
    'xml.etree',
    'xml.etree.ElementTree',
    'html',
    'html.parser',
    'csv',
    'configparser',
    'argparse',
    'gettext',
    'locale',
    'codecs',
    'encodings',
    'hashlib',
    'hmac',
    'secrets',
    'base64',
    'binascii',
    'struct',
    'array',
    'heapq',
    'bisect',
    'enum',
    'typing',
    'inspect',
    'traceback',
    'warnings',
    'weakref',
    'copy',
    'pprint',
    'reprlib',
    'abc',
    'contextlib',
    'sqlite3',
    'pytz',
    'dateutil',
    'dateutil.parser',
    'dateutil.tz',
]

a = Analysis(
    ['botiaver1.py'],
    pathex=[],
    binaries=xgboost_binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=['tests', 'pytest', 'matplotlib', 'pandas.tests', 'scipy', 'distutils', 'certbot', 'acme', 'pyopenssl', 'cryptography', 'setuptools', 'pkg_resources', 'jaraco', 'zipp', 'importlib_metadata', 'importlib_resources', 'wheel', 'pip', 'platformdirs', 'tomli', 'docutils', 'pygments', 'markdown', 'distlib'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
    optimize=2,
    collect_submodules=['sklearn', 'xgboost', 'numpy', 'pandas'],
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='MT5TradingBot_v1',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

